version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=testDB
    ports:
      - '5440:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: